name: atcs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py38h294d835_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2020.12.5=h5b45459_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2020.12.5=py38haa244fe_1
  - cffi=1.14.5=py38hcd4344a_0
  - chardet=4.0.0=py38haa95532_1003
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py38h71e12ea_0
  - cudatoolkit=10.2.89=h74a9793_1
  - dataclasses=0.8=pyhc8e2a94_1
  - filelock=3.0.12=pyh9f0ad1d_0
  - fsspec=2021.4.0=pyhd8ed1ab_0
  - future=0.18.2=py38haa244fe_3
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.37.1=py38he5377a8_0
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=4.0.1=py38haa244fe_0
  - intel-openmp=2021.2.0=haa95532_616
  - joblib=1.0.1=pyhd8ed1ab_0
  - libprotobuf=3.15.8=h7755175_0
  - libuv=1.40.0=he774522_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.3.0=py38h2bbff1b_1
  - mkl_fft=1.3.0=py38h277e83a_2
  - mkl_random=1.2.1=py38hf11a4ad_2
  - multidict=5.1.0=py38h294d835_1
  - ninja=1.10.2=h6d14046_1
  - numpy=1.20.1=py38h34a8a5c_0
  - numpy-base=1.20.1=py38haf7ebc8_0
  - oauthlib=3.0.1=py_0
  - openssl=1.1.1k=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pip=21.0.1=py38haa95532_0
  - protobuf=3.15.8=py38h885f38d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.8=hdbf39b2_5
  - python_abi=3.8=1_cp38
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7_0
  - pytorch-lightning=1.2.10=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h294d835_0
  - regex=2021.4.4=py38h294d835_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - sacremoses=0.0.43=pyh9f0ad1d_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.35.4=h2bbff1b_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tokenizers=0.10.1=py38h291c280_0
  - torchmetrics=0.3.1=pyhd8ed1ab_0
  - torchtext=0.9.1=py38
  - tqdm=4.59.0=pyhd3eb1b0_1
  - transformers=4.5.1=pyhd8ed1ab_1
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38_0
  - yaml=0.2.5=he774522_0
  - yarl=1.6.3=py38h294d835_1
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - pip:
    - higher==0.2.1
prefix: C:\Programs\miniconda3\envs\atcs
